# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tuist-build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Tuist-build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tuist/tuist-action@0.13.0
      with:
        command: 'fetch'
    - uses: tuist/tuist-action@0.13.0
      with: 
        command: 'build'
        arguments: ''
